/*
 * This example source was generated by PhoneGap android create script
 * then modified to use BrightContext
 * All BrightContext modifications MIT licensed
 */

/*
 * Automatically generated phonegap license:
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    onDeviceReady: function() {
        app.receivedEvent('deviceready');

        // once the device is ready, open a connection to the platform
        app.openFeeds();
    },
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    },
    openFeeds: function() {
        app.project = BCC.init('my api key').project('my project');

        app.project.feed({
            channel: 'my thru channel',
            onopen: function (f) {
                app.receivedEvent('feedopen');

                f.send({ "hello" : "phonegap" });
            },
            onmsgsent: function (f, msg) {
                console.log(msg);
                app.receivedEvent('messagesent');
            },
            onmsgreceived: function (f, msg) {
                console.log(msg);
                app.receivedEvent('messagereceived');

                f.close();
            },
            onclose: function () {
                app.receivedEvent('feedclosed');
            }
        });

        // for more examples, see the hosted JavaScript documenation:
        // http://www.brightcontext.com/docs/js/
    }
};
